"""empty message

Revision ID: 109705bd5aab
Revises: 6d095c4908a9
Create Date: 2021-02-23 18:16:13.375706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109705bd5aab'
down_revision = '6d095c4908a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
