"""empty message

Revision ID: 5497a9b66065
Revises: 2af177c16e97
Create Date: 2021-02-24 18:43:58.879988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5497a9b66065'
down_revision = '2af177c16e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.add_column('show_association_table', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('show_association_table', sa.Column('show_id', sa.Integer(), nullable=True))
    op.add_column('show_association_table', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_association_table_Artist_fkey', 'show_association_table', type_='foreignkey')
    op.drop_constraint('show_association_table_Show_fkey', 'show_association_table', type_='foreignkey')
    op.drop_constraint('show_association_table_Venue_fkey', 'show_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'show_association_table', 'Show', ['show_id'], ['id'])
    op.create_foreign_key(None, 'show_association_table', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'show_association_table', 'Artist', ['artist_id'], ['id'])
    op.drop_column('show_association_table', 'Show')
    op.drop_column('show_association_table', 'Venue')
    op.drop_column('show_association_table', 'Artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_association_table', sa.Column('Artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('show_association_table', sa.Column('Venue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('show_association_table', sa.Column('Show', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show_association_table', type_='foreignkey')
    op.drop_constraint(None, 'show_association_table', type_='foreignkey')
    op.drop_constraint(None, 'show_association_table', type_='foreignkey')
    op.create_foreign_key('show_association_table_Venue_fkey', 'show_association_table', 'Venue', ['Venue'], ['id'])
    op.create_foreign_key('show_association_table_Show_fkey', 'show_association_table', 'Show', ['Show'], ['id'])
    op.create_foreign_key('show_association_table_Artist_fkey', 'show_association_table', 'Artist', ['Artist'], ['id'])
    op.drop_column('show_association_table', 'venue_id')
    op.drop_column('show_association_table', 'show_id')
    op.drop_column('show_association_table', 'artist_id')
    op.add_column('Show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
