"""empty message

Revision ID: a8eaee3a9120
Revises: 109705bd5aab
Create Date: 2021-02-24 03:15:32.585547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8eaee3a9120'
down_revision = '109705bd5aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_association_table',
    sa.Column('Show', sa.Integer(), nullable=True),
    sa.Column('Artist', sa.Integer(), nullable=True),
    sa.Column('Venue', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Artist'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Show'], ['Show.id'], ),
    sa.ForeignKeyConstraint(['Venue'], ['Venue.id'], )
    )
    op.add_column('Show', sa.Column('past_or_upcomming', sa.String(), nullable=True))
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('Show', 'past_or_upcomming')
    op.drop_table('show_association_table')
    # ### end Alembic commands ###
