"""empty message

Revision ID: b9767983b044
Revises: 6b400f2ce4ed
Create Date: 2021-02-22 15:37:49.245719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9767983b044'
down_revision = '6b400f2ce4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Artist',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=True),
    # sa.Column('city', sa.String(length=120), nullable=True),
    # sa.Column('state', sa.String(length=120), nullable=True),
    # sa.Column('phone', sa.String(length=120), nullable=True),
    # sa.Column('genres', sa.String(length=120), nullable=True),
    # sa.Column('image_link', sa.String(length=500), nullable=True),
    # sa.Column('facebook_link', sa.String(length=120), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('Venue',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=True),
    # sa.Column('city', sa.String(length=120), nullable=True),
    # sa.Column('state', sa.String(length=120), nullable=True),
    # sa.Column('address', sa.String(length=120), nullable=True),
    # sa.Column('phone', sa.String(length=120), nullable=True),
    # sa.Column('image_link', sa.String(length=500), nullable=True),
    # sa.Column('facebook_link', sa.String(length=120), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
